services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: v2hub_app
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:1.25-alpine
    container_name: v2hub_nginx
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    env_file:
      - .env

    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/entrypoint/grafana-config.sh:/docker-entrypoint.d/20-grafana-config.sh:ro
      - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
      - ./nginx/grafana.htpasswd:/etc/nginx/grafana.htpasswd:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro

    depends_on:
      app:
        condition: service_healthy

  # ── promtail удалён, заменён на alloy ──
  alloy:
    profiles:
      - enabled
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    expose:
      - "12345"
    volumes:
      - ./monitoring/alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock # Docker API для дискавери
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345 # включаем UI
      - --stability.level=generally-available
    privileged: true # нужно для чтения Docker сокета

  loki:
    profiles:
      - enabled
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    expose:
      - "3100"
    volumes:
      - ./monitoring/loki.yml:/etc/loki/local-config.yaml
      - lokidata:/loki

  prometheus:
    profiles:
      - enabled
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    expose:
      - "9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus

  grafana:
    profiles:
      - enabled
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=https://panel.v2hub.link/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./monitoring/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafanadata:/var/lib/grafana

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  grafanadata:
  prometheusdata:
  lokidata:
